wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.12/apache-maven-3.9.12-bin.zip

spring.datasourse.url=jdbc:h2:mem:taskdb
spring.datasourse.driver-class-name=org.h2.Driver
spring.datasourse.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true